# Generated by Django 3.1.2 on 2020-10-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='migrantes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=30)),
                ('pais_origen', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('fecha_migracion', models.DateField()),
                ('documento', models.IntegerField()),
            ],
        ),
    ]
